version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: booking_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: booking_api_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/booking_db?schema=public
      - JWT_SECRET=123456
      - NODE_ENV=production
    depends_on:
      - db

volumes:
  postgres_data: